# -- 대여 시작일을 기준으로,
# -- 2022~8월부터 2022년 10월까지 대여 횟수가 5회 이상인ㄴ 자동차들
# -- 월별 자동차 id별 총 대여 횟수
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 8 AND 10
AND CAR_ID IN
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID
HAVING COUNT(*) >= 5
)
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH(START_DATE), CAR_ID DESC


# SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) COUNT
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE MONTH(START_DATE) BETWEEN 8 AND 10
# AND CAR_ID IN (SELECT CAR_ID
#                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                WHERE MONTH(START_DATE) BETWEEN 8 AND 10
#                GROUP BY CAR_ID
#                HAVING COUNT(*) > 4)
# GROUP BY CAR_ID, MONTH(START_DATE)
# ORDER BY MONTH ASC, CAR_ID DESC;
